version: '3'

services:
    airflow:
        build:
            context: ./airflow
        command: 'true'
        image: libero/airflow:latest
    airflow-flower:
        build:
            context: ./airflow
        depends_on:
            - airflow
            - airflow-redis
        environment:
            - EXECUTOR=Celery
            - REDIS_HOST=airflow-redis
        ports:
            - "5555:5555"
        command: flower
    airflow-postgres:
        image: postgres:9.6.8-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - airflow-postgres:/var/lib/postgresql/data
    airflow-redis:
        image: 'redis:3.2.7'
    airflow-scheduler:
        build:
            context: ./airflow
        depends_on:
            - airflow
            - airflow-webserver
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=airflow-postgres
            - REDIS_HOST=airflow-redis
        command: scheduler
    airflow-webserver:
        build:
            context: ./airflow
        depends_on:
            - airflow
            - airflow-postgres
            - airflow-redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=airflow-postgres
            - REDIS_HOST=airflow-redis
        ports:
            - "8086:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    airflow-worker:
        build:
            context: ./airflow
        depends_on:
            - airflow
            - airflow-scheduler
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_HOST=airflow-postgres
            - REDIS_HOST=airflow-redis
        command: worker

    db:
        image: postgres:10.4
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: $DATABASE_NAME
            POSTGRES_USER: $DATABASE_USER
            POSTGRES_PASSWORD: $DATABASE_PASSWORD

    csv-generator:
        build:
            context: ./csv-generator
        command: '--help'
        image: data-pipeline/csv-generator:${IMAGE_TAG}
        volumes:
            - ./example-data:/example-data
            - xml-data:/xml-data
            - ./csv-data:/csv-data

    db-manager:
        build:
            context: ./db-manager
        command: ''
        image: data-pipeline/db-manager:${IMAGE_TAG}
        depends_on:
            - db
        environment:
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_NAME: $DATABASE_NAME
            DATABASE_USER: $DATABASE_USER
            DATABASE_PASSWORD: $DATABASE_PASSWORD

volumes:
    airflow-postgres:
    postgres-data:
    xml-data: 
    csv-data:
