sequenceDiagram
  dim Manuscript Version ->> dim Manuscript Version History: cascadeActivations
  dim Manuscript Version ->> dim Manuscript: registerInitialisations
  dim Manuscript Version ->> dim Manuscript: cascadeActivations

